---
project:
  type: website

format:
  html:
    theme: darkly
  revealjs:
    filters:
      - _filters/slugify.lua
    footer: "{{< meta title >}} - {{< var author.website.talks >}}"
    hash-type: number
    history: false
    incremental: true
    link-external-icon: true
    mermaid:
      theme: dark
    slide-number: true
    theme: dark
    transition: fade

website:
  google-analytics: G-SCSTN0WCDT
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: "{{< var author.website.home >}}"
      - icon: github
        href: "{{< var author.website.talks >}}"
  title: ""
