project:
  type: website

website:
  title: ""
  site-path: /talks/
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    toc: true
  revealjs:
    incremental: true
    theme: moon
