project:
  type: website

format:
  html:
    theme: darkly
  revealjs:
    footer: <https://paddyroddy.github.io/talks>
    incremental: true
    theme: moon
    transition: slide

website:
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/talks
  site-path: /talks/
  title: ""
