---
project:
  type: website

format:
  html:
    theme: darkly
  revealjs:
    footer: >-
      {{< meta title >}}:
      <https://paddyroddy.github.io/talks>{.external target="_blank"}
    incremental: true
    slide-number: true
    transition: slide

website:
  google-analytics: G-SCSTN0WCDT
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/talks
  repo-url: https://github.com/paddyroddy/talks
  site-url: https://paddyroddy.github.io/talks
  title: ""
