project:
  type: website

website:
  favicon: /assets/images/favicon.ico
  site-path: /talks/
  title: ""
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/talks

format:
  html:
    theme: darkly
  revealjs:
    incremental: true
    theme: moon
