---
project:
  type: website

format:
  html:
    theme: darkly
  revealjs:
    footer: "{{< meta title >}}: <https://paddyroddy.github.io/talks>"
    incremental: true
    link-external-icon: true
    link-external-newwindow: true
    slide-number: true
    theme: dark
    transition: fade

website:
  google-analytics: G-SCSTN0WCDT
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
        target: _blank
      - icon: github
        href: https://github.com/paddyroddy/talks
        target: _blank
  title: ""
