---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@c97ca7c448df211268616ce438777228fe103733 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/vale@c97ca7c448df211268616ce438777228fe103733 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
