---
name: Quarto Publish

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/quarto@95df55339346244d6434eda9edfc05d53aa6c9cc # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          requirements-txt: ${{ github.workspace }}/requirements.txt
