---
name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/quarto@5db0473ebf89b7132850d118505c172be8022f97 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
