---
name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/quarto@553e2cabff4290dd6283ae235489c0150be98d91 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
