---
name: Quarto Publish

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: paddyroddy/.github/actions/github-pages/quarto@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
