---
name: Quarto Publish

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/quarto@b45ffef611d12e0263916cf6f650a9b2cc13aa4f # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
